export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
python run_bert.py \
--model_type bert \
--model_name_or_path model_85% \
--do_train \
--do_eval \
--do_test \
--data_dir ./data/data_3 \
--output_dir ./model_roberta_splitnum6_seqlength128_batch64_step15000_3 \
--max_seq_length 128 \
--split_num 6 \
--lstm_hidden_size 512 \
--lstm_layers 1 \
--lstm_dropout 0.12 \
--eval_steps 200 \
--per_gpu_train_batch_size 1 \
--gradient_accumulation_steps 1 \
--warmup_steps 0 \
--per_gpu_eval_batch_size 32 \
--learning_rate 5e-6 \
--adam_epsilon 1e-6 \
--weight_decay 0 \
--train_steps 10000
